# Generated by Django 5.0.6 on 2026-07-01 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', '進行中'), ('passed', '合格'), ('failed', '不合格'), ('aborted', '中止')], default='in_progress', max_length=20, verbose_name='ステータス')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='スコア')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='開始日時')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenger_sessions', to=settings.AUTH_USER_MODEL, verbose_name='挑戦者')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='guild.company', verbose_name='会社')),
            ],
            options={
                'verbose_name': '面談セッション',
                'verbose_name_plural': '面談セッション',
                'ordering': ['-created_at'],
            },
        ),
    ]
