# Generated by Django 5.0.6 on 2026-07-15 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0002_interviewsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('interviewer', '面接官(AI)'), ('challenger', '挑戦者')], max_length=20, verbose_name='発言者')),
                ('message', models.TextField(verbose_name='発言内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='発言日時')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatlogs', to='guild.interviewsession', verbose_name='面接セッション')),
            ],
            options={
                'verbose_name': '発言ログ',
                'verbose_name_plural': '発言ログ一覧',
                'ordering': ['created_at'],
            },
        ),
    ]
