# Generated by Django 5.0.6 on 2026-07-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0003_chatlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='タグ名')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ一覧',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='companies', to='guild.tag', verbose_name='タグ'),
        ),
    ]
