# Generated by Django 5.0.6 on 2026-09-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0004_tag_company_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='judge_comment',
            field=models.TextField(blank=True, default='', verbose_name='講評'),
        ),
    ]
